aadil_dbt:
  outputs:
    dev:
      catalog: dbt_learning_catalog
      host: dbc-76aa188c-9424.cloud.databricks.com
      http_path: /sql/1.0/warehouses/5f899a64caea63a5
      schema: dbt_learning
      threads: 1
      token: dapiaebfb194509f65fa46c650c290655d4d
      type: databricks
  target: dev
aws_dbt_snowflake_project:
  outputs:
    dev:
      account: BMDPGER-RV28327
      database: AIRBNB
      password: Aadil@12345678
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: AADIL111
      warehouse: COMPUTE_WH
  target: dev
dbt_snowflake_aws_project:
  outputs:
    dev:
      account: BMDPGER-RV28327
      database: AIRBNB_PRO
      password: Aadil@12345678
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: AADIL111
      warehouse: COMPUTE_WH
  target: dev
