aadil_dbt:
  outputs:
    dev:
      catalog: sample_catalog
      host: example-databricks-host.cloud.databricks.com
      http_path: /sql/1.0/warehouses/XXXXXXXXXXXX
      schema: sample_schema
      threads: 1
      token: DUMMY_DATABRICKS_TOKEN
      type: databricks
  target: dev

aws_dbt_snowflake_project:
  outputs:
    dev:
      account: SAMPLE_ACCOUNT_ID
      database: SAMPLE_DATABASE
      password: DUMMY_PASSWORD
      role: SAMPLE_ROLE
      schema: sample_schema
      threads: 1
      type: snowflake
      user: SAMPLE_USER
      warehouse: SAMPLE_WAREHOUSE
  target: dev

dbt_snowflake_aws_project:
  outputs:
    dev:
      account: SAMPLE_ACCOUNT_ID
      database: SAMPLE_DATABASE_PRO
      password: DUMMY_PASSWORD
      role: SAMPLE_ROLE
      schema: sample_schema
      threads: 1
      type: snowflake
      user: SAMPLE_USER
      warehouse: SAMPLE_WAREHOUSE
  target: dev
