sources:
  - name: STAGING
    database: AIRBNB_PRO
    schema: STAGING
    tables:
        - name: bookings
          columns:
          - name: booking_id
            data_tests:
              - unique
              - not_null
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}
          loaded_at_field: created_at
        - name: hosts
        - name: listings
